// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"nnjcivzn1e","name":"remindersCRUD","description":"","endpoint":"https://nnjcivzn1e.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/reminders","/reminders/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:d836e4cc-958d-4c27-adf6-d7391b91d302',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'alexamobileremindera-hosting-mobilehub-2034174961',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dobcu3t77v01q.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"alexamobileremindera-mobilehub-2034174961-reminders","attributes":[{"name":"userId","type":"S"},{"name":"task","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mobile_analytics_app_id': '7d0e6943243f47bb8e1b8aa43ec77083',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a5de4590-b54e-4cbc-a5ef-488cccc4e0cc',
    'aws_project_name': 'alexa-mobile-reminder-app',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'alexamobileremindera-deployments-mobilehub-2034174961',
    'aws_resource_name_prefix': 'alexamobileremindera-mobilehub-2034174961',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_cYBzNTlC4',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '4ungf7kn0ifvbqpepe91oja1md',
}

export default awsmobile;
