// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:3313eb39-7633-4531-bab3-341482788d88',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'alexamobileremindera-hosting-mobilehub-326693963',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd6q90t7e6je3h.cloudfront.net',
    'aws_mobile_analytics_app_id': 'ab7f9cbb50324ac3a09a1a75af2c3a5f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '85fb7ac8-4f05-4ce5-b8bb-e85e0b37eab8',
    'aws_project_name': 'alexa-mobile-reminder-app',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'alexamobileremindera-mobilehub-326693963',
}

export default awsmobile;
