// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:5cc84aa2-c6c2-49ad-a6c3-bcfb0076a8b5',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'alexamobileremindera-hosting-mobilehub-2119044487',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1mehkaee6xmmn.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a75c2d8bc7344e21a434921240ec570e',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '18080d9e-76ea-4b0b-8a62-45ab07703638',
    'aws_project_name': 'alexa-mobile-reminder-app',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'alexamobileremindera-mobilehub-2119044487',
}

export default awsmobile;
