// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"4ivtym6eke","name":"RemindersCRUD","description":"","endpoint":"https://4ivtym6eke.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/Reminders","/Reminders/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:c67e526e-c651-4f3b-97e2-ea76e1c806c1',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'alexamobileremindera-hosting-mobilehub-1286098681',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3c8b2658ak84w.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"alexamobileremindera-mobilehub-1286098681-Reminders","attributes":[{"name":"userId","type":"S"},{"name":"task","type":"S"},{"name":"taskId","type":"N"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '8b2427744bee4ee4aeb20a018486c39f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c422f0c3-973d-4d22-950e-0da2a469f7ff',
    'aws_project_name': 'alexa-mobile-reminder-app',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'alexamobileremindera-deployments-mobilehub-1286098681',
    'aws_resource_name_prefix': 'alexamobileremindera-mobilehub-1286098681',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_cNdjgQPEb',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '4213dmlk6fn3kv28ue17cuqtdo',
}

export default awsmobile;
